In [1]:
import pandas as pd;
import numpy as np;

In [4]:
df=pd.read_csv("E:\Python\Finance Planning\Finance-Planning\ml-service\datasets\customer_financial_profiles_500.csv")

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\shiva\AppData\Local\Temp\ipykernel_17308\149711292.py:1: SyntaxWarning: invalid escape sequence '\P'
  df=pd.read_csv("E:\Python\Finance Planning\Finance-Planning\ml-service\datasets\customer_financial_profiles_500.csv")

In [5]:
df

,customer_id,age,occupation,dependents,monthly_income,monthly_expenses,monthly_debt_payment,monthly_savings,cash_savings,existing_investments,...,investment_experience,risk_score,financial_goal,goal_amount,current_goal_savings,goal_gap,time_horizon_years,preferred_investment,savings_rate,debt_to_income_ratio
0,C0001,23,Bank Employee,1,58700,18656,8144,31900,251665,1721270,...,Beginner,3.7,Wealth Creation,4520271,488813,4031458,15,Bonds,54.34,13.87
1,C0002,49,Software Engineer,2,60764,36962,10297,13505,556987,1570160,...,Beginner,3.1,Child Education,4396927,1570160,2826767,12,FD,22.23,16.95
2,C0003,55,Accountant,1,66749,30021,14643,22085,741412,1493414,...,Beginner,3.5,Retirement,3868278,1343652,2524626,6,FD,33.09,21.94
3,C0004,59,Designer,4,83817,60105,9238,14474,673521,857181,...,Intermediate,6.3,Wealth Creation,3835615,618156,3217459,11,Hybrid MF,17.27,11.02
4,C0005,38,Designer,2,94683,50733,21285,22665,729173,580897,...,Beginner,2.9,Wealth Creation,4668847,729173,3939674,15,Bonds,23.94,22.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,C0496,21,Teacher,1,64458,20974,2641,40843,504355,1697781,...,Intermediate,6.9,Wealth Creation,5034681,1697781,3336900,8,Hybrid MF,63.36,4.10
496,C0497,41,Designer,4,67438,35063,0,32375,336027,1136023,...,Beginner,5.9,Retirement,7316861,572909,6743952,12,Gold,48.01,0.00
497,C0498,52,Accountant,1,69635,44509,12083,13043,492196,1887538,...,Advanced,3.7,Retirement,7771513,532557,7238956,14,PPF,18.73,17.35
498,C0499,46,Business Owner,3,192728,113342,50551,28835,1508906,4946829,...,Beginner,6.7,Retirement,5964118,2460482,3503636,7,Hybrid MF,14.96,26.23
499,C0500,53,Teacher,4,57563,28823,5143,23597,489193,1603379,...,Beginner,8.3,Wealth Creation,3472130,587041,2885089,8,Equity MF,40.99,8.93

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            500 non-null    object
 1   age                    500 non-null    int64
 2   occupation             500 non-null    object
 3   dependents             500 non-null    int64
 4   monthly_income         500 non-null    int64
 5   monthly_expenses       500 non-null    int64
 6   monthly_debt_payment   500 non-null    int64
 7   monthly_savings        500 non-null    int64
 8   cash_savings           500 non-null    int64
 9   existing_investments   500 non-null    int64
 10  property_value         500 non-null    int64
 11  other_assets           500 non-null    int64
 12  total_assets           500 non-null    int64
 13  total_liabilities      500 non-null    int64
 14  net_worth              500 non-null    int64
 15  emergency_fund         500 non-null    int64
 16  insurance_coverage     500 non-null    int64
 17  credit_score           500 non-null    int64
 18  risk_tolerance         500 non-null    object
 19  investment_experience  500 non-null    object
 20  risk_score             500 non-null    float64
 21  financial_goal         500 non-null    object
 22  goal_amount            500 non-null    int64
 23  current_goal_savings   500 non-null    int64
 24  goal_gap               500 non-null    int64
 25  time_horizon_years     500 non-null    int64
 26  preferred_investment   500 non-null    object
 27  savings_rate           500 non-null    float64
 28  debt_to_income_ratio   500 non-null    float64
dtypes: float64(3), int64(20), object(6)
memory usage: 113.4+ KB

In [9]:
df.isnull().sum()

customer_id              0
age                      0
occupation               0
dependents               0
monthly_income           0
monthly_expenses         0
monthly_debt_payment     0
monthly_savings          0
cash_savings             0
existing_investments     0
property_value           0
other_assets             0
total_assets             0
total_liabilities        0
net_worth                0
emergency_fund           0
insurance_coverage       0
credit_score             0
risk_tolerance           0
investment_experience    0
risk_score               0
financial_goal           0
goal_amount              0
current_goal_savings     0
goal_gap                 0
time_horizon_years       0
preferred_investment     0
savings_rate             0
debt_to_income_ratio     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

,age,dependents,monthly_income,monthly_expenses,monthly_debt_payment,monthly_savings,cash_savings,existing_investments,property_value,other_assets,...,emergency_fund,insurance_coverage,credit_score,risk_score,goal_amount,current_goal_savings,goal_gap,time_horizon_years,savings_rate,debt_to_income_ratio
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,5.000000e+02,5.000000e+02,5.000000e+02,5.000000e+02,...,500.000000,5.000000e+02,500.000000,500.000000,5.000000e+02,5.000000e+02,5.000000e+02,500.000000,500.000000,500.000000
mean,40.832000,1.810000,85042.926000,43102.714000,10491.972000,31450.314000,5.986808e+05,1.410759e+06,2.376314e+06,3.401220e+05,...,193737.256000,2.236562e+06,726.880000,6.091000,4.777123e+06,8.134199e+05,3.963703e+06,9.616000,37.003260,12.271120
std,11.747331,1.254211,33890.891864,19194.765222,7654.155012,16798.086313,3.476162e+05,9.074893e+05,2.736822e+06,2.492048e+05,...,119950.995895,1.928029e+06,52.071148,2.123685,2.536801e+06,5.389318e+05,2.293512e+06,3.339888,12.318381,6.555236
min,21.000000,0.000000,25403.000000,10000.000000,0.000000,0.000000,8.796400e+04,1.507110e+05,0.000000e+00,2.151000e+03,...,16741.000000,0.000000e+00,583.000000,2.300000,2.089360e+05,2.623800e+04,1.277520e+05,3.000000,0.000000,0.000000
25%,30.000000,1.000000,60931.250000,29497.500000,5302.500000,19961.750000,3.375240e+05,7.580030e+05,0.000000e+00,1.405562e+05,...,103316.500000,0.000000e+00,691.000000,4.000000,3.008278e+06,4.225260e+05,2.190965e+06,7.000000,28.260000,7.507500
50%,41.000000,2.000000,76015.000000,38437.500000,9300.500000,28400.000000,5.181165e+05,1.204427e+06,1.038974e+06,2.902345e+05,...,169228.500000,2.077566e+06,726.000000,6.200000,4.651862e+06,7.176165e+05,3.818626e+06,9.000000,36.960000,12.155000
75%,51.000000,3.000000,101533.500000,54473.750000,13892.750000,38943.750000,7.842308e+05,1.856759e+06,4.686932e+06,4.759258e+05,...,256531.000000,3.462986e+06,760.000000,7.100000,6.760104e+06,1.106508e+06,5.652053e+06,13.000000,45.827500,17.082500
max,60.000000,4.000000,199420.000000,113342.000000,50551.000000,116388.000000,2.036431e+06,5.024180e+06,7.985562e+06,1.288703e+06,...,740783.000000,9.066048e+06,850.000000,10.000000,9.982792e+06,2.921971e+06,9.262626e+06,15.000000,65.510000,29.460000

In [11]:
df.describe(include="object")

,customer_id,occupation,risk_tolerance,investment_experience,financial_goal,preferred_investment
count,500,500,500,500,500,500
unique,500,10,3,3,7,10
top,C0001,Government Employee,Moderate,Intermediate,Wealth Creation,Equity MF
freq,1,54,249,231,144,104

In [7]:
df.risk_score.max()

np.float64(10.0)

In [8]:
df.groupby(['age']).risk_score.mean()

age
21    6.490000
22    5.914286
23    6.047059
24    7.415789
25    6.466667
26    6.220000
27    5.993333
28    5.783333
29    6.475000
30    6.788889
31    5.566667
32    5.942857
33    5.450000
34    4.710000
35    6.562500
36    5.650000
37    5.518182
38    6.392857
39    6.022222
40    6.452941
41    5.105556
42    6.783333
43    6.140000
44    5.650000
45    5.975000
46    6.464706
47    6.440000
48    5.253846
49    5.884615
50    6.550000
51    5.726667
52    6.528571
53    6.252632
54    5.491667
55    6.055556
56    6.769231
57    6.308333
58    5.684615
59    5.875000
60    6.336842
Name: risk_score, dtype: float64

In [14]:
calculated_savings = (
    df["monthly_income"]
    - df["monthly_expenses"]
    - df["monthly_debt_payment"]
)

(df["monthly_savings"] == calculated_savings).all()

np.False_